import Head from 'next/head'

import React, { useState, useEffect } from 'react';
import {
    Drawer, useMediaQuery, Box, PaletteMode, Typography
} from '@mui/material';
import { createTheme, responsiveFontSizes, ThemeProvider } from '@mui/material/styles';

import SnackBar from '../Utilities/SnackBar';
import "inter-ui/inter.css";

const theme = createTheme({
    palette: {
        primary: {
            main: "#451AE0",
        },
        secondary: {
            main: "#E2E200",
        },
    },
    typography: {
        fontFamily: [
            'Inter',
            'system-ui',
            /* 'Arial',
            'serif', */
        ].join(','),
    },
  });

const Layout = ({ children }) => {

    return (
        <div>
            <Head>
                <title>Virtual PT</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
                    rel="stylesheet" />
            </Head>
            <Box>
                    <ThemeProvider theme={theme}>
                        {children}
                    </ThemeProvider>
            </Box>
            <SnackBar />
        </div>
    )
}

export default Layout
