
import Head from 'next/head'

import React, { useState, useEffect } from 'react';
import { useRouter } from 'next/router'
import {
  Drawer, useMediaQuery, Box, PaletteMode, Typography, Grid, Container, CircularProgress, CssBaseline
} from '@mui/material';
import { useDispatch, useSelector } from "react-redux";
import { useTheme } from '@mui/material/styles';

import Layout from '../components/GeneralComponents/Blocks/Layout';

const Home = () => {

  const dispatch = useDispatch();
  const router = useRouter();
  const userReducer = useSelector((state) => state.userReducer);

  useEffect(() => {
    console.log("React working...");
    
  }, [userReducer.currentUser])


  const [openDrawer, setOpenDrawer] = useState(false)
  const [open, setOpen] = useState(false)
  const theme = useTheme();
  const isMobile = useMediaQuery(theme.breakpoints.down('sm'));

  useEffect(() => {

    /* if (isMobile) {
      setOpenDrawer(true)
    } */

  }, [isMobile])

  return (
    <>
      <Head>
        <title>Virtual PT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet" />
      </Head>
      <Grid container component="main" sx={{
        height: '100vh'
      }}>
        <CssBaseline />
        <Grid item xs={12} >
          <Box
            display="flex"
            alignItems="center"
            justifyContent="center"
            sx={{
              height: '100vh',
              backgroundColor: (theme) => theme.palette.background.default
            }}>
            Index
          </Box>
        </Grid>
      </Grid>
    </>

  )
}

Home.getLayout = (page) => (
  <Layout>
    {page}
  </Layout>
)

export default Home
